// const x = 10;
// const y = 8;
// let c = x + y;
// console.log("bodlogo1", c);
// const a = 10;
// const b = 4;
// console.log("bodlogo 2", a - b);
// const p = 7;
// const q = 6;
// console.log("bodlogo 3", p * q);
// const m = 20;
// const n = 5;
// console.log("bodlogo 4", m / n);
// const x = 15;
// const y = 4;
// console.log("bodlogo 5", x % y);
// num = 10;
// console.log("bodlogo 6", num + 5);
// num = 20;
// console.log("bodlogo 7", (num += 10));
// num = 50;
// console.log("bodlogo 8", (num -= 20));
// num = 6;
// console.log("bodlogo 8", (num *= 3));
// num = 16;
// console.log("bodlogo 10", (num /= 4));
// console.log("bodlogo #2");
// const heighth = 3;
// const widthh = 4;
// const lengthh = 5;
// console.log("triangle p", lengthh + widthh + lengthh);
// console.log("bodlogo 2", 1 + 3 + 5 + 7 + 8.7);
// const urt = 10;
// const orgon = 5;
// console.log("bodlogo 3", (urt + orgon) * 2);
// console.log("bodlogo 4", (98 % 60) / 100 + 1);
// console.log("bodlogo 5.1 tsag", (1297 / 60 / 60) % 60);
// console.log("bodlogo 5.2 minut", Math.floor(1297 / 60) % 60);
// console.log("bodlogo 5.3 second", Math.floor(1297 % 60));
// const remaininsecond = 88;
// const numminute = 875;
// console.log("bodlogo 6", numminute * 60 + remaininsecond);
// const remaintime = 83;
// const remainminute = 84;
// const numsecond = 85;
// console.log("bodlogo7", remaintime * 3600 + remainminute * 60 + numsecond);
const remainhour = 38;
console.log("bodlogo 1 uldeh tsag", remainhour % 24);
console.log("bodlogo 1 uldeh honog", Math.floor(remainhour / 24));
const remainday = 4;
const remainddhour = 40;
console.log("bodlogo2 niit tsag", remainday * 24 + remainddhour);
const remainmonth = 106;
console.log("bodlogo3 jil", Math.floor(remainmonth / 12));
const remainyear = 8;
console.log("bodlogo3 sar", 106 - remainyear * 12);
console.log("bodlogo4", 9 > 3 > 2 < 8);
